#!/bin/sh
#
# @name E-flite Convergence (Control Allocation)
#
# @type VTOL Tiltrotor
# @class VTOL
#
# @maintainer Silvan Fuhrer <silvan.fuhrer@hotmail.com>
#
# @output MAIN1 Motor right
# @output MAIN2 Motor left
# @output MAIN3 Motor back
# @output MAIN4 empty
# @output MAIN5 Tilt servo right
# @output MAIN6 Tilt servo left
# @output MAIN7 Elevon right
# @output MAIN8 Elevon left
#
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

sh /etc/init.d/rc.vtol_defaults
sh /etc/init.d/rc.ctrlalloc

if [ $AUTOCNF = yes ]
then


	param set MPC_USE_HTE 0

	param set VM_MASS 0.9
	param set VM_INERTIA_XX 0.015
	param set VM_INERTIA_YY 0.02
	param set VM_INERTIA_ZZ 0.04

	param set CA_AIRFRAME 2
	param set CA_METHOD 1
	param set CA_ACT0_MIN 0.0
	param set CA_ACT1_MIN 0.0
	param set CA_ACT2_MIN 0.0
	param set CA_ACT3_MIN -1.0
	param set CA_ACT4_MIN -1.0
	param set CA_ACT0_MAX 1.0
	param set CA_ACT1_MAX 1.0
	param set CA_ACT2_MAX 1.0
	param set CA_ACT3_MAX 1.0
	param set CA_ACT4_MAX 1.0



	param set SYS_USE_IO 0
	param set CBRK_IO_SAFETY 22027
	param set COM_PREARM_MODE 0

	param set FW_ARSP_MODE 2

	param set FW_L1_PERIOD 17
	param set FW_MAN_R_MAX 50
	param set FW_ACRO_X_MAX   270
	param set FW_ACRO_Y_MAX   270
	param set FW_ACRO_Z_MAX   180
	param set FW_PR_FF    0.5
	param set FW_PR_P 0.08
	param set FW_PSP_OFF  5
	param set FW_P_LIM_MAX    30
	param set FW_P_LIM_MIN    -30
	param set FW_P_RMAX_NEG   60
	param set FW_P_RMAX_POS   60
	param set FW_RR_FF    0.33
	param set FW_RR_P 0.11
	param set FW_YR_FF    0.3
	param set FW_YR_P 0.05

	param set MC_YAWRATE_P 0.3
	param set MPC_LAND_SPEED 1.2
	param set MPC_TKO_SPEED 2.5
	param set MPC_Z_VEL_MAX_UP 3

	param set SENS_BOARD_ROT 8

	param set VT_B_TRANS_DUR  1
	param set VT_F_TRANS_DUR  1.2
	param set VT_F_TR_OL_TM   4
	param set VT_TILT_FW  1
	param set VT_TILT_MC  0
	param set VT_TILT_TRANS   0.45
	param set VT_TRANS_MIN_TM 1.2
	param set VT_TRANS_P2_DUR 1.3
	param set VT_TYPE 1
fi

set MIXER simple_direct
set PWM_OUT 123
