#!/bin/sh
#
# @name Generic Tailsitter
#
# @type VTOL Duo Tailsitter
# @class VTOL
#
# @output MAIN1 motor right
# @output MAIN2 motor left
# @output MAIN5 elevon right
# @output MAIN6 elevon left
#
# @maintainer Silvan Fuhrer <silvan.fuhrer@hotmail.com>
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

sh /etc/init.d/rc.vtol_defaults
sh /etc/init.d/rc.ctrlalloc


if [ $AUTOCNF = yes ]
then

	param set VM_MASS 0.25
	param set VM_INERTIA_XX 0.0035
	param set VM_INERTIA_YY 0.0007
	param set VM_INERTIA_ZZ 0.003

	param set CA_AIRFRAME 4
	param set CA_METHOD 1
	param set CA_ACT0_MIN 0.0
	param set CA_ACT1_MIN 0.0
	param set CA_ACT2_MIN -1.0
	param set CA_ACT3_MIN -1.0
	param set CA_ACT0_MAX 1.0
	param set CA_ACT1_MAX 1.0
	param set CA_ACT2_MAX 1.0
	param set CA_ACT3_MAX 1.0


	param set FW_AIRSPD_MIN 10
	param set FW_AIRSPD_TRIM 13
	param set FW_AIRSPD_MAX 20

	param set VT_ELEV_MC_LOCK 0
	param set VT_MOT_COUNT 2
	param set VT_TYPE 0

	param set MAV_TYPE 19

	# set disarmed value for the ESC
	param set PWM_DISARMED 1000

	param set SYS_USE_IO 0
	param set CBRK_IO_SAFETY 22027
	param set COM_PREARM_MODE 0
fi

set MIXER direct
set PWM_OUT 12

set MIXER_AUX direct_aux
set PWM_AUX_OUT 12
