/****************************************************************************
 *
 *   Copyright (c) 2019 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

/**
 * @file mixer_thrust_vectoring.cpp
 *
 * Mixer for Thrust Vector Control.
 */

#include "mixer.h"

#include <float.h>
#include <cstring>
#include <cstdio>

#include <mathlib/mathlib.h>

#ifdef MIXER_TVC_USE_MOCK_GEOMETRY
enum class TvcGeometry : TvcGeometryUnderlyingType {
	QUAD_X,
	MAX_GEOMETRY
};
namespace
{
const TvcMixer::Alloc_Vect _config_quad_x[] = {
	{ -1.000000,  1.000000,  1.000000 },
	{ -1.000000, -1.000000,  1.000000 },
	{  1.000000, -1.000000,  1.000000 },
	{  1.000000,  1.000000,  1.000000 },
};
const TvcMixer::Alloc_Vect *_config_index[] = {
	&_config_quad_x[0]
};
const unsigned _config_actuator_count[] = {5};
const char *_config_key[] = {"4x"};
}

#else

// This file is generated by the px_generate_mixers.py script which is invoked during the build process
#include "mixer_thrust_vectoring_normalized.h"

#endif /* MIXER_TVC_USE_MOCK_GEOMETRY */


#define debug(fmt, args...)	do { } while(0)
//#define debug(fmt, args...)	do { printf("[mixer] " fmt "\n", ##args); } while(0)
//#include <debug.h>
//#define debug(fmt, args...)	syslog(fmt "\n", ##args)

TvcMixer::TvcMixer(ControlCallback control_cb,
		   uintptr_t cb_handle,
		   TvcGeometry geometry) :
	Mixer(control_cb, cb_handle),
	_thrust_factor(0.0f),
	_airmode(Airmode::disabled),
	_actuator_count(_config_actuator_count[(TvcGeometryUnderlyingType)geometry]),
	_fins_count(_actuator_count - 1),
	_alloc_mat(_config_index[(TvcGeometryUnderlyingType)geometry]),
	_tmp_array(new float[_actuator_count])
{
}
TvcMixer::TvcMixer(ControlCallback control_cb,
		   uintptr_t cb_handle,
		   Alloc_Vect *alloc_mat,
		   unsigned actuator_count) :
	Mixer(control_cb, cb_handle),
	_thrust_factor(0.0f),
	_airmode(Airmode::disabled),
	_actuator_count(actuator_count),
	_alloc_mat(alloc_mat),
	_tmp_array(new float[_actuator_count])
{
}

TvcMixer::~TvcMixer()
{
	delete[] _tmp_array;
}

TvcMixer *
TvcMixer::from_text(Mixer::ControlCallback control_cb, uintptr_t cb_handle, const char *buf, unsigned &buflen)
{
	TvcGeometry geometry = TvcGeometry::MAX_GEOMETRY;
	char geomname[8];
	int used;

	/* enforce that the mixer ends with a new line */
	if (!string_well_formed(buf, buflen)) {
		return nullptr;
	}

	if (sscanf(buf, "V: %7s%n", geomname, &used) != 1) {
		debug("TVC parse failed on '%s'", buf);
		return nullptr;
	}

	if (used > (int)buflen) {
		debug("OVERFLOW: TVC spec used %d of %u", used, buflen);
		return nullptr;
	}

	buf = skipline(buf, buflen);

	if (buf == nullptr) {
		debug("no line ending, line is incomplete");
		return nullptr;
	}

	debug("remaining in buf: %d, first char: %c", buflen, buf[0]);

	for (TvcGeometryUnderlyingType i = 0; i < (TvcGeometryUnderlyingType)TvcGeometry::MAX_GEOMETRY;
	     i++) {
		if (!strcmp(geomname, _config_key[i])) {
			geometry = (TvcGeometry)i;
			break;
		}
	}

	if (geometry == TvcGeometry::MAX_GEOMETRY) {
		debug("unrecognised geometry '%s'", geomname);
		return nullptr;
	}

	debug("adding TVC mixer '%s'", geomname);

	return new TvcMixer(
		       control_cb,
		       cb_handle,
		       geometry);
}

float TvcMixer::compute_desaturation_gain(const float *desaturation_vector, const float *outputs,
		saturation_status &sat_status, float min_output, float max_output) const
{
	float k_min = 0.f;
	float k_max = 0.f;

	for (unsigned i = 0; i < _fins_count; i++) {
		// Avoid division by zero. If desaturation_vector[i] is zero, there's nothing we can do to unsaturate anyway
		if (fabsf(desaturation_vector[i]) < FLT_EPSILON) {
			continue;
		}

		if (outputs[i] < min_output) {
			float k = (min_output - outputs[i]) / desaturation_vector[i];

			if (k < k_min) { k_min = k; }

			if (k > k_max) { k_max = k; }

			sat_status.flags.motor_neg = true;
		}

		if (outputs[i] > max_output) {
			float k = (max_output - outputs[i]) / desaturation_vector[i];

			if (k < k_min) { k_min = k; }

			if (k > k_max) { k_max = k; }

			sat_status.flags.motor_pos = true;
		}
	}

	// Reduce the saturation as much as possible
	return k_min + k_max;
}

void TvcMixer::minimize_saturation(const float *desaturation_vector, float *outputs,
				   saturation_status &sat_status,
				   float min_output, float max_output, bool reduce_only) const
{
	float k1 = compute_desaturation_gain(desaturation_vector, outputs, sat_status, min_output, max_output);

	if (reduce_only && k1 > 0.f) {
		return;
	}

	for (unsigned i = 0; i < _fins_count; i++) {
		outputs[i] += k1 * desaturation_vector[i];
	}

	// Compute the desaturation gain again based on the updated outputs.
	// In most cases it will be zero. It won't be if max(outputs) - min(outputs) > max_output - min_output.
	// In that case adding 0.5 of the gain will equilibrate saturations.
	float k2 = 0.5f * compute_desaturation_gain(desaturation_vector, outputs, sat_status, min_output, max_output);

	for (unsigned i = 0; i < _fins_count; i++) {
		outputs[i] += k2 * desaturation_vector[i];
	}
}

void TvcMixer::thrust_boost(float thrust, float *outputs, saturation_status &sat_status, float min_output,
			    float max_output)
{
	// Boost gain to unsaturate the actuators
	// As the thrust scales linearly the control effectiveness
	// matrix, the thrust is simply scaled by the gain required to unsaturate
	// the most saturated actuator
	// This gain should at be at least 1
	// TODO: warning, min and max have to be non-zero and symmetrical around zero
	float k_max = 1.f;

	for (unsigned i = 0; i < _fins_count; i++) {
		if (outputs[i] < min_output) {
			float k = outputs[i] / min_output;

			if (k > k_max) { k_max = k; }

		} else if (outputs[i] > max_output) {
			float k = outputs[i] / max_output;

			if (k > k_max) { k_max = k; }
		}
	}

	// Scale and constrain thrust
	float thrust_new = k_max * thrust;

	if (thrust_new > 1.f) {
		thrust_new = 1.f;
		sat_status.flags.motor_pos = true;
	}

	outputs[_fins_count] = thrust_new;

	// Adjust the outputs for the new thrust
	float k_sat = thrust_new / thrust;

	for (unsigned i = 0; i < _fins_count; i++) {
		outputs[i] /= k_sat;
	}
}

void TvcMixer::mix_airmode_rp(float roll, float pitch, float yaw, float thrust, float *outputs)
{
	// Airmode for roll and pitch, but not yaw

	// Mix without yaw
	for (unsigned i = 0; i < _fins_count; i++) {
		outputs[i] = roll * _alloc_mat[i].roll_scale / thrust +
			     pitch * _alloc_mat[i].pitch_scale / thrust;
	}

	thrust_boost(thrust, outputs, _saturation_status, -1.f, 1.f);

	// Mix yaw independently
	mix_yaw(yaw, thrust, outputs);
}

void TvcMixer::mix_airmode_rpy(float roll, float pitch, float yaw, float thrust, float *outputs)
{
	// Airmode for roll, pitch and yaw

	// Do full mixing
	for (unsigned i = 0; i < _fins_count; i++) {
		outputs[i] = roll * _alloc_mat[i].roll_scale / thrust +
			     pitch * _alloc_mat[i].pitch_scale / thrust +
			     yaw * _alloc_mat[i].yaw_scale / thrust;
	}

	thrust_boost(thrust, outputs, _saturation_status, -1.f, 1.f);

	// Unsaturate yaw (in case upper and lower bounds are exceeded)
	// to prioritize roll/pitch over yaw.
	// We don't need to scale the yaw scale with thrust here since the
	// desaturation logic only needs the direction and not the norm
	for (unsigned i = 0; i < _fins_count; i++) {
		_tmp_array[i] = _alloc_mat[i].yaw_scale;
	}

	minimize_saturation(_tmp_array, outputs, _saturation_status, -1.f, 1.f);
}

void TvcMixer::mix_airmode_disabled(float roll, float pitch, float yaw, float thrust, float *outputs)
{
	// Airmode disabled: never allow to increase the thrust to unsaturate an actuator

	// Mix without yaw
	for (unsigned i = 0; i < _fins_count; i++) {
		outputs[i] = roll * _alloc_mat[i].roll_scale / thrust +
			     pitch * _alloc_mat[i].pitch_scale / thrust;
	}

	// Reduce roll/pitch acceleration if needed to unsaturate
	for (unsigned i = 0; i < _fins_count; i++) {
		_tmp_array[i] = _alloc_mat[i].roll_scale;
	}

	minimize_saturation(_tmp_array, outputs, _saturation_status, -1.f, 1.f);

	for (unsigned i = 0; i < _fins_count; i++) {
		_tmp_array[i] = _alloc_mat[i].pitch_scale;
	}

	minimize_saturation(_tmp_array, outputs, _saturation_status, -1.f, 1.f);

	// Mix yaw independently
	mix_yaw(yaw, thrust, outputs);
}

void TvcMixer::mix_yaw(float yaw, float thrust, float *outputs)
{
	// Add yaw to outputs
	for (unsigned i = 0; i < _fins_count; i++) {
		outputs[i] += yaw * _alloc_mat[i].yaw_scale / thrust;

		// Yaw will be used to unsaturate if needed
		_tmp_array[i] = _alloc_mat[i].yaw_scale;
	}

	// Change yaw acceleration to unsaturate the outputs if needed (do not change roll/pitch),
	minimize_saturation(_tmp_array, outputs, _saturation_status, -1.f, 1.f);
}

unsigned
TvcMixer::mix(float *outputs, unsigned space)
{
	float roll    = math::constrain(get_control(0, 0), -1.0f, 1.0f);
	float pitch   = math::constrain(get_control(0, 1), -1.0f, 1.0f);
	float yaw     = math::constrain(get_control(0, 2), -1.0f, 1.0f);
	// Set minimum thrust to 0.01 to avoid division by zero
	float thrust  = math::constrain(get_control(0, 3), 0.01f, 1.0f);

	// clean out class variable used to capture saturation
	_saturation_status.value = 0;

	// Apply thrust to first output, mapping is always 1-to-1
	outputs[_fins_count] = thrust;

	// Do the mixing using the strategy given by the current Airmode configuration
	switch (_airmode) {
	case Airmode::roll_pitch:
		mix_airmode_rp(roll, pitch, yaw, thrust, outputs);
		break;

	case Airmode::roll_pitch_yaw:
		mix_airmode_rpy(roll, pitch, yaw, thrust, outputs);
		break;

	case Airmode::disabled:
	default: // just in case: default to disabled
		mix_airmode_disabled(roll, pitch, yaw, thrust, outputs);
		break;
	}

	// Apply thrust model and scale outputs to range [0, 1].
	// At this point the outputs are expected to be in [0, 1]
	// Implement simple model for static relationship between applied motor pwm and motor thrust
	// model: thrust = (1 - _thrust_factor) * PWM + _thrust_factor * PWM^2
	if (_thrust_factor > 0.0f) {
		outputs[0] = -(1.0f - _thrust_factor) / (2.0f * _thrust_factor) + sqrtf((1.0f - _thrust_factor) *
				(1.0f - _thrust_factor) / (4.0f * _thrust_factor * _thrust_factor) + (outputs[0] < 0.0f ? 0.0f : outputs[0] /
						_thrust_factor));
	}

	// Rescale thruster output from [0, 1] to [-1, 1]
	outputs[_fins_count] = math::constrain(2.f * outputs[0] - 1.f, -1.f, 1.f);

	for (unsigned i = 0; i < _fins_count; i++) {
		outputs[i] = math::constrain(outputs[i], -1.f, 1.0f);
	}

	// Saturation checking
	for (unsigned i = 0; i < _fins_count; i++) {
		bool clipping_high = false;
		bool clipping_low_roll_pitch = false;
		bool clipping_low_yaw = false;

		// Check for saturation against static limits.
		// We only check for low clipping if airmode is disabled (or yaw
		// clipping if airmode==roll/pitch), since in all other cases thrust will
		// be reduced or boosted and we can keep the integrators enabled, which
		// leads to better tracking performance.
		if (outputs[i] < 0.01f) {
			if (_airmode == Airmode::disabled) {
				clipping_low_roll_pitch = true;
				clipping_low_yaw = true;

			} else if (_airmode == Airmode::roll_pitch) {
				clipping_low_yaw = true;
			}
		}

		// update the saturation status report
		update_saturation_status(i, clipping_high, clipping_low_roll_pitch, clipping_low_yaw);
	}

	return _actuator_count;
}

/*
 * This function update the control saturation status report using the following inputs:
 *
 * index: 0 based index identifying the motor that is saturating
 * clipping_high: true if the motor demand is being limited in the positive direction
 * clipping_low_roll_pitch: true if the motor demand is being limited in the negative direction (roll/pitch)
 * clipping_low_yaw: true if the motor demand is being limited in the negative direction (yaw)
*/
void
TvcMixer::update_saturation_status(unsigned index, bool clipping_high, bool clipping_low_roll_pitch,
				   bool clipping_low_yaw)
{
	// The motor is saturated at the upper limit
	// check which control axes and which directions are contributing
	if (clipping_high) {
		if (_alloc_mat[index].roll_scale > 0.0f) {
			// A positive change in roll will increase saturation
			_saturation_status.flags.roll_pos = true;

		} else if (_alloc_mat[index].roll_scale < 0.0f) {
			// A negative change in roll will increase saturation
			_saturation_status.flags.roll_neg = true;
		}

		// check if the pitch input is saturating
		if (_alloc_mat[index].pitch_scale > 0.0f) {
			// A positive change in pitch will increase saturation
			_saturation_status.flags.pitch_pos = true;

		} else if (_alloc_mat[index].pitch_scale < 0.0f) {
			// A negative change in pitch will increase saturation
			_saturation_status.flags.pitch_neg = true;
		}

		// check if the yaw input is saturating
		if (_alloc_mat[index].yaw_scale > 0.0f) {
			// A positive change in yaw will increase saturation
			_saturation_status.flags.yaw_pos = true;

		} else if (_alloc_mat[index].yaw_scale < 0.0f) {
			// A negative change in yaw will increase saturation
			_saturation_status.flags.yaw_neg = true;
		}

		// A positive change in thrust will increase saturation
		_saturation_status.flags.thrust_pos = true;

	}

	// The motor is saturated at the lower limit
	// check which control axes and which directions are contributing
	if (clipping_low_roll_pitch) {
		// check if the roll input is saturating
		if (_alloc_mat[index].roll_scale > 0.0f) {
			// A negative change in roll will increase saturation
			_saturation_status.flags.roll_neg = true;

		} else if (_alloc_mat[index].roll_scale < 0.0f) {
			// A positive change in roll will increase saturation
			_saturation_status.flags.roll_pos = true;
		}

		// check if the pitch input is saturating
		if (_alloc_mat[index].pitch_scale > 0.0f) {
			// A negative change in pitch will increase saturation
			_saturation_status.flags.pitch_neg = true;

		} else if (_alloc_mat[index].pitch_scale < 0.0f) {
			// A positive change in pitch will increase saturation
			_saturation_status.flags.pitch_pos = true;
		}

		// A negative change in thrust will increase saturation
		_saturation_status.flags.thrust_neg = true;
	}

	if (clipping_low_yaw) {
		// check if the yaw input is saturating
		if (_alloc_mat[index].yaw_scale > 0.0f) {
			// A negative change in yaw will increase saturation
			_saturation_status.flags.yaw_neg = true;

		} else if (_alloc_mat[index].yaw_scale < 0.0f) {
			// A positive change in yaw will increase saturation
			_saturation_status.flags.yaw_pos = true;
		}
	}

	_saturation_status.flags.valid = true;
}

void
TvcMixer::set_airmode(Airmode airmode)
{
	_airmode = airmode;
}

void
TvcMixer::groups_required(uint32_t &groups)
{
	/* XXX for now, hardcoded to indexes 0-3 in control group zero */
	groups |= (1 << 0);
}

uint16_t TvcMixer::get_saturation_status()
{
	return _saturation_status.value;
}
